### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by Flashlab2** [MvRens/ha-enever#3]
I have updated the template for my EV-Charging sensor like mentioned:

```
      ...
      attributes:
        prices_today: "{{ state_attr('sensor.enever_stroomprijs_nextenergy', 'prices_today') }}"
        prices_tomorrow: "{{ state_attr('sensor.enever_stroomprijs_nextenergy', 'prices_tomorrow') }}"
```

But this gives a wrong format for the time info:
`
[{'time': datetime.datetime(2025, 1, 7, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Amsterdam')), 'price': 0.168367}
`

How can I fix this?
